# Generated by Django 3.2 on 2022-10-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoinginvoice',
            name='product_kai_by_amount',
        ),
    ]
