# Generated by Django 3.2 on 2022-10-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producedproduct',
            old_name='product_kai_by_amount',
            new_name='used_human_one_amount',
        ),
        migrations.AddField(
            model_name='producedproduct',
            name='used_human_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_human_one_id', to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producedproduct',
            name='used_human_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_human_two_id', to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producedproduct',
            name='used_human_two_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producedproduct',
            name='used_resource_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_resource_one_id', to='product.stockproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producedproduct',
            name='used_resource_one_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producedproduct',
            name='used_resource_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_resource_two_id', to='product.stockproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producedproduct',
            name='used_resource_two_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
