# Generated by Django 3.2 on 2022-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221001_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedproduct',
            name='metadata_hash',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
