# Generated by Django 3.2 on 2022-10-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_producedproduct_metadata_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedproduct',
            name='tx_hash',
            field=models.CharField(default=1, max_length=66),
            preserve_default=False,
        ),
    ]
